// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bigbaldy1129

//@version=4
strategy("My RSI for DCA", overlay=true)

startTime = input(timestamp("08 01 2021 00:00 +0800"),type=input.time)
endTime = input(timestamp("01 01 2100 00:00 +0800"),type=input.time)

isDate = time >= startTime and time <= endTime                    
    
showDate   = input(true, title = "Show Date Range", type = input.bool)
showTimeE  = input(true, title = "Show Time Entry", type = input.bool)
showTimeX  = input(true, title = "Show Time Exit", type = input.bool)

length = input( 7 )
overSold = input( 50 )
deviation  = input(1.2)
deviationScale = input(1.0)
fillMaxCount = input(6)
volumeScale = input(1.3)
targetProfit = input(1.2)
showRange = input(false, title = "Show Range", type = input.bool)
openNewTradeAsap = input(false)

f_print(_text) =>
    var _label = label.new(bar_index, na, _text, xloc.bar_index, yloc.price, color(na), label.style_none, color.green, size.large, text.align_left)
    label.set_xy(_label, bar_index, highest(10)[0] + 10)
    label.set_text(_label, _text)

price = close
vrsi = rsi(price, length)
buy = vrsi < overSold
if openNewTradeAsap
    buy := true
var sell = false
var buyPrice = price
var totalPrice = price
var meanPrice = price
var buyCount = 0
var totalVolume = 1.0
var add = false
var _targetProfit = 1 + targetProfit / 100.0
var profit = price - price
var maxVolume = price - price
if not maxVolume
    for i = 1 to fillMaxCount
        maxVolume := maxVolume + pow(volumeScale, i - 1)

if buy and not buyCount and isDate
    buyPrice := price
    totalPrice := price
    meanPrice := price
    buyCount := buyCount + 1
    buy := true
else
    buy := false

currentBuyPrice = price
if deviationScale == 1
    currentBuyPrice := buyPrice * (1 - deviation * buyCount / 100.0)
else
    currentBuyPrice := buyPrice * (1 - deviation * (1 - pow(deviationScale, buyCount))/(1 - deviationScale) / 100.0)
    
if buyCount and buyCount <= fillMaxCount and close < currentBuyPrice
    buyCount := buyCount + 1
    volumeDelta = pow(volumeScale, buyCount - 1)
    totalVolume := totalVolume + volumeDelta
    totalPrice := totalPrice + currentBuyPrice * volumeDelta
    meanPrice := totalPrice / totalVolume
    label.new(bar_index, low, text="F" + tostring(buyCount - 1), style=label.style_label_up, color=color.green, textcolor=color.white, size=size.tiny)

if buyCount and close / meanPrice >= _targetProfit
    profit := profit + totalVolume * (close / meanPrice - 1.00075) / maxVolume
    sell := true
    buyCount := 0
    totalVolume := 1
    meanPrice := 0
else
    sell := false
if (not na(vrsi))
	strategy.entry("buy", true, when = isDate and buy)
    strategy.close("buy", when = isDate and sell, comment='sell')
    
f_print("mean_price: " + tostring(meanPrice) + "\n" + "buy_count: " + tostring(buyCount)+"\n"+"profit: "+tostring(profit))

transp = showRange ? 95: 100
bgcolor(color = showDate and isDate ? color.gray : na,transp = transp)
bgcolor(color = showTimeE and isDate ? color.lime : na,transp = transp)
bgcolor(color = showTimeX and isDate ? color.purple : na,transp = transp)